# Generated by Django 3.0.8 on 2020-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
